export const characters = [
  {"id": "character-shun", "name": "Shun", "age": 13, "gender": "Male", "birthday": "September 9", "nationality": "Japanese", "training": "Andromeda Island", "masters": ["Daidalos", "Albior"], "attacks": ["Nebula Chain", "Rolling Defense", "Andromeda Nebula", "Circle Defense ", "Wild Trap", "Spiral Duct", "Spider Net", "Boomerang Shot", "Casting Net", "Great Capture", "Thunder Wave", "Nebula Stream", "Nebula Storm"], "height(cm)": 165, "weight(kg)": 51},
  {"id": "character-paradise", "name": "Paradise", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Camus", "name": "Camus", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Dégel", "name": "Dégel", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Krest", "name": "Krest", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Mystoria", "name": "Mystoria", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Tokisada", "name": "Tokisada", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Marin", "name": "Marin", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Yuna", "name": "Yuna", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Hakurei", "name": "Hakurei", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Nikol", "name": "Nikol", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Avenir", "name": "Avenir", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Guateguard", "name": "Guateguard", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Kiki", "name": "Kiki", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": ["Mu"], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Mu", "name": "Mu", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": ["Shion"], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Shion", "name": "Shion", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Capella", "name": "Capella", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Almaaz", "name": "Almaaz", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Bayer", "name": "Bayer", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Michelangelo", "name": "Michelangelo", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Bartschius", "name": "Bartschius", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-contador-da-morte-de-cancer", "name": "Contador da Morte de Câncer", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Lancelot", "name": "Lancelot", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Manigold", "name": "Manigold", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-death-mask", "name": "Death Mask", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Sage", "name": "Sage", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Schiller", "name": "Schiller", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Asterion", "name": "Asterion", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Miguel", "name": "Miguel", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Sírius", "name": "Sírius", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-El-cid ", "name": "El Cid ", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Shura", "name": "Shura", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Ionia", "name": "Ionia", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Izo", "name": "Izo", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Atlas", "name": "Atlas", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Elda", "name": "Elda", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Babel", "name": "Babel", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Alfa", "name": "Alfa", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Mouses", "name": "Mouses", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Menkar", "name": "Menkar", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-June", "name": "June", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Hook", "name": "Hook", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Gray", "name": "Gray", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Berengue", "name": "Berengue", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Mei", "name": "Mei", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Dali", "name": "Dali", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Katya", "name": "Katya", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Jamian", "name": "Jamian", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Johan", "name": "Johan", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Suikyô", "name": "Suikyô", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Georg", "name": "Georg", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Kazuma", "name": "Kazuma", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-christ", "name": "Christ", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Hyoga", "name": "Hyoga", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Isaak", "name": "Isaak", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Guney", "name": "Guney", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Mii", "name": "Mii", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Spear", "name": "Spear", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Shiryu", "name": "Shiryu", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Ryuho", "name": "Ryuho", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Celeris", "name": "Celeris", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Kitalpha", "name": "Kitalpha", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Subaru", "name": "Subaru", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Kyoko", "name": "Kyoko", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Shoko", "name": "Shoko", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Abel", "name": "Abel", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Cain", "name": "Cain", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Aspros", "name": "Aspros", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Defteros", "name": "Defteros", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Kanon", "name": "Kanon", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Paradox", "name": "Paradox", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Saga", "name": "Saga", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Komachi", "name": "Komachi", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Yuzuriha", "name": "Yuzuriha", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Algethi", "name": "Algethi", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Curtis", "name": "Curtis", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Ichi", "name": "Ichi", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Misty", "name": "Misty", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Aiolia", "name": "Aiolia", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Ilias", "name": "Ilias", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Kaiser", "name": "Kaiser", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Micenas", "name": "Micenas", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Regulus", "name": "Regulus", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Ban", "name": "Ban", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Bleriot", "name": "Bleriot", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Souma", "name": "Souma", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Arne", "name": "Arne", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Dohko", "name": "Dohko", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Shiryu", "name": "Shiryu", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Gembu", "name": "Gembu", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Itia", "name": "Itia", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Haruto", "name": "Haruto", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Yoshitomi", "name": "Yoshitomi", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Junkers", "name": "Junkers", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Nachi", "name": "Nachi", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Jaô", "name": "Jaô", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Mirapolos", "name": "Mirapolos", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Retsu", "name": "Retsu", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Orfeu", "name": "Orfeu", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Jabu", "name": "Jabu", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Yato", "name": "Yato", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Dio", "name": "Dio", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Fly", "name": "Fly", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Luciano", "name": "Luciano", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Shina", "name": "Shina", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Odisseu", "name": "Odisseu", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Eden", "name": "Eden", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Rigel", "name": "Rigel", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Jaga", "name": "Jaga", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Mayura", "name": "Mayura", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Plavin", "name": "Plavin", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Shiva", "name": "Shiva", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Seiya", "name": "Seiya", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Tenma", "name": "Tenma", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Kouga", "name": "Kouga", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Algol", "name": "Algol", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Mirfak", "name": "Mirfak", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Ikki", "name": "Ikki", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Albafica", "name": "Albafica", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Afrodite", "name": "Afrodite", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Amor", "name": "Amor", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Cardinale", "name": "Cardinale", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Lugonis", "name": "Lugonis", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Lacaille", "name": "Lacaille", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Rusk", "name": "Rusk", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Berlozzo", "name": "Berlozzo", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Tremy", "name": "Tremy", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Maiya", "name": "Maiya", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Archon", "name": "Archon", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Siam", "name": "Siam", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Aiolos", "name": "Aiolos", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Gestalt", "name": "Gestalt", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Sísifo", "name": "Sísifo", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Milo", "name": "Milo", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Escarlate", "name": "Escarlate", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Kardia", "name": "Kardia", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Sonia", "name": "Sonia", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Zafiri", "name": "Zafiri", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Ennead", "name": "Ennead", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Juan", "name": "Juan", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Yan", "name": "Yan", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Yuuri", "name": "Yuuri", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Aldebaran", "name": "Aldebaran", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Francisca", "name": "Francisca", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Harbinger", "name": "Harbinger", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Hasgard", "name": "Hasgard", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Ox", "name": "Ox", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Teneo", "name": "Teneo", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Noesis", "name": "Noesis", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Geki", "name": "Geki", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Douglas", "name": "Douglas", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Xiaoling", "name": "Xiaoling", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Tsubaki", "name": "Tsubaki", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Shaka", "name": "Shaka", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Asmita", "name": "Asmita", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Fudou", "name": "Fudou", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Shijima", "name": "Shijima", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Argo", "name": "Argo", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Rudolph", "name": "Rudolph", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Dante", "name": "Dante", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Dorer", "name": "Dorer", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Partita", "name": "Partita", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Ágora", "name": "Ágora", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Aracne", "name": "Aracne", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Spartan", "name": "Spartan", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Reda", "name": "Reda", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Spika", "name": "Spika", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Dócrates", "name": "Dócrates", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Píton", "name": "Píton", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Gigars", "name": "Gigars", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Jisty", "name": "Jisty", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Daichi", "name": "Daichi", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Emma", "name": "Emma", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Erna", "name": "Erna", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Kerry", "name": "Kerry", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Shô", "name": "Shô", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Ushô", "name": "Ushô", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Allegre", "name": "Allegre", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Don Avido", "name": "Don Avido", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Guilty", "name": "Guilty", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Jango", "name": "Jango", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Jid", "name": "Jid", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Kenuma", "name": "Kenuma", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Lemargos", "name": "Lemargos", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Lumaca", "name": "Lumaca", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Ritahoa", "name": "Ritahoa", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Rusé", "name": "Rusé", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Shinadekuro", "name": "Shinadekuro", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-Yudo", "name": "Yudo", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-", "name": "", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0},
  {"id": "character-", "name": "", "age": 0, "gender": "", "birthday": "", "nationality": "", "training": "", "masters": [], "attacks": [], "height": 0, "weight": 0}
];

    "Gigas": [
      {"TitanServants":
        [
          {"Lyax de Poinx": {}},
          {"Phlox de Cianos": {}},
          {"Anemos de Leucotes": {}},
          {"Bronte de Melas": {}},
          {"Spate de Paios": {}},
          {"Zugilos de Anthrakma":{}},
          {"Margarites de Dragão de Pérola": {}},
          {"Electron de Fera Âmbar": {}},
          {"Nephiritis de Couraça de Jade": {}}
        ]
      },
      {"TifonServants": 
        [
          {"Ágrios (Força Brutal)": {}},
          {"Toas (Relâmpago Célebre)": {}},
          {"Pallas (Parvo)": {}},
          {"Encélado": [
            {"Encélado (Brado de Combate)": {"Midia": "Gigantomaquia"}},
            {"Encélado": {"Midia": "Lost Canvas"}}]},
          {"Ortos (Cão Bicéfalo do Mal)": {}},
          {"Quimera (Fera Pluriforme)": {}},
          {"Ladon (Dragão de Cem Cabeças)": {}},
          {"Equidina (Mulher Giga)": {}},
          {"Tifon": [
            {"Tífon": {"Midia": "Lost Canvas"}},
            {"Tífon": {"Midia": "Episódio G"}},
            {"Tífon": {"Midia": "Gigantomaquia"}}
          ]}
        ]
      }
    ],
    "Titãs": {
      "Os 12 Titãs": [
        {"Céos (Relâmpago Negro)": {}},
        {"Créos (Galáxia)": {}},
        {"Cronos": [
          {"Cronos": {"Midia": "Next Dimension"}},
          {"Cronos (Tempo)": {"Midia": "Episode G"}},
          {"Saturno": {"Midia": "Ômega"}}]},
        {"Febe (Lua)": {}},
        {"Hyperion (Ébano)": {}},
        {"Iápeto (Dimensões)": {}},
        {"Mnemôsine (Memória)": {}},
        {"Oceano (Dilúvio)": {}},
        {"Réia (Mãe dos Deuses)": {}},
        {"Téia (Luz e Fogo)": {}},
        {"Têmis (Justiça)": {}},
        {"Tétis (Mar)": {}}
      ],
      "Outros titãs": [
        {"Atlas": {}},
        {"Euríbia": {}},
        {"Prometeu": {}}
      ]
    },
    "Fadas de Balor": [{"Shelley de Banshee": {}}],
    "Dríades": [
      {"Ate de Ruína": {}},
      {"Disnomia": {}},
      {"Emony de Malícia": {}},
      {"Mania de Loucura": {}},
      {"Phonos de Assassinato": {}},
      {"Banimento/Punição": {"Máscara da Morte": {}}}
    ],
    "Taonias": [
      {"Feiyan de Hakutaku": {}},
      {"Hakuryu": {}},
      {"Hui de Kyuubi": {}},
      {"Liu Xing": {}},
      {"Mudan de Pardal": {}},
      {"Taonias de alto escalão": {}},
      {"Taonias de baixo escalão": {}}
    ], 
    "Pítias": [
      {"Arches": {}},
      {"Ninfas (Pítias)": {}}
    ],
    "Berserkers": [
      {"Ema de Jamadhar": {}},
      {"Kokalo de Buhj": {}}
    ],
    "Jóias": [
      {"Chaceldony de Ilusões": {}},
      {"Cornelian de Sangue da Carne Cortada": {}},
      {"Flint de Punhos Flamejantes": {}},
      {"Garnet de Vouivre": {}},
      {"Krest de Koh-Í-Noor": {}},
      {"Tourmaline de Eletricidade": {}}
    ],
    "Jaguares": [
      {"Nahualpilli de Youaltepuztli": {}},
      {"Jaguares": {}}
    ],
    "Satélites": [
      {"Calisto": {}},
      {"Rasku Moon": {}},
      {"Satélite #1": {}},
      {"Satélite #2": {}},
      {"Satélite #3": {}},
      {"Satélite #4": {}},
      {"Satélite #5": {}},
      {"Satélite #6": {}},
      {"Satélite #7": {}},
      {"Satélite #8": {}}
    ],
    "Marcianos": [
      {"Medea": {}},
      {"Ordykia de Mantis": {}},
      {"Radzinsky de Formiga": {}},
      {"Ragno de Aranha": {}},
      {"Sonia de Vespa": {}},
      {"Comandante Marciano": {}},
      {"Escaravelho #1": {}},
      {"Escaravelho #2": {}},
      {"Baco": {}},
      {"Diana": {}},
      {"Rômulo": {}},
      {"Vulcano": {}}
    ],
    "Pallasitos": {
      "FirstClass": [
        {"Titan de Espada da Criação": {}},
        {"Hyperion de Espada da Destruição": {}},
        {"Gália de Espada da Guerra": {}},
        {"Aigaion de Espada do Trovão": {}}        
      ],
      "SecondClass": [
        {"Dione de Cobra de Plasma (Chicote)": {}},
        {"Réia de Marionetes": {}},
        {"Europa de Corte Retalhador (Chakram)": {}},
        {"Aegir de Braço Fantasma (Manopla)": {}},
        {"Paradox de Jano Escarlate (Cetro)": {}},
        {"Surtr de Pedra Mística": {}},
        {"Tokisada de Relógio da Morte": {}}
      ],
      "ThirdClass": [
        {"Tarvos de Esmagador de Estrelas (Mangual)": {}},
        {"Loge de Brionac (Lança)": {}},
        {"Ymir de Máxima Brilhante (Garras)": {}},
        {"Metone de Máxima Brilhante (Garras)": {}},
        {"Halimede (Barra Tripla)": {}},
        {"Hati (Adaga)": {}},
        {"Tebe de Impacto Demoníaco (Martelo)": {}},
        {"Cilene de Matador de Almas (Foice da Morte)": {}},
        {"Greip de Matador de Almas (Foice da Morte)": {}},
        {"Eden de Maça de Impulso (Clava)": {}}
      ],
      "UnknownClass": [
        {"Miller de Luva Alquímica": {}}
      ],
      "FourthClass": [
        {"Green": {"Master": "Titan de Espada da Criação"}},
        {"Red": {"Master": "Hyperion de Espada da Destruição"}},
        {"Yellow": {"Master": "Gália de Espada da Guerra"}},
        {"Blue": {"Master": "Aigaion de Espada do Trovão"}},
        {"Black": {"Master": "(Ômega) Saturno"}}
      ]
    },
    "Sem Face": [
      {"Sem Face Ceifador de Almas": {}},
      {"Sem Face Dragão": {}},
      {"Sem Face Piromaníaco": {}},
      {"Wadatsumi": {}}
    ],
    "Gladiadores": [
      {"Alice de Vorpal": {}},
      {"Lancelot de Arondight": {}},
      {"Paracelsus de Azoth": {}},
      {"Roland de Durandal": {}},
      {"Sigurd de Gram": {}}
    ], 
    "BlueWarriors": [
      {"Alexei": {}},
      {"Garcia": {}},
      {"Natássia": {}},
      {"Piotr": {}},
      {"Soldados de Alexei": {}}
    ],
    "GodWarriors": {
      "Liderados por Durval": [
        {"Durval": {}},
        {"Frey": {}},
        {"Loki": {}},
        {"Midgard": {}},
        {"Ur": {}},
        {"Rung": {}}
      ],
      "Liderados por Hilda": [
        {"Hilda de Polaris": {}},
        {"Alberich de Megrez (Delta)": {}},
        {"Fenrir de Alioth (Epsílon)": {}},
        {"Hagen de Merak (Beta)": {}},
        {"Mime de Benetnasch (Eta)": {}},
        {"Bado de Arkor (Zeta)": {}},
        {"Shido de Mizar (Zeta)": {}},
        {"Siegfried de Dubhe (Alfa)": {}},
        {"Thor de Phecda (Gama)": {}}
      ],
      "Liderados por Andreas": [
        {"Andreas": {}},
        {"Sigmund de Granyl": {}},
        {"Surt de Eikschnir": {}},
        {"Utgardar de Garm": {}},
        {"Balder de Hraesvelgr": {}},
        {"Fafner de Nidhogg": {}},
        {"Frodi de Gullinbursti": {}},
        {"Hércules de Tanngrisnir": {}}
      ]
    }, 
    "Marinas de Poseison": {
      "Marinas": {"Sereia": [{"Thetis": {}}]},
      "Generais Marinas": {
        "Dragão Marinho": [{"Kanon": {}}, {"Unity": {}}],
        "Cavalo Marinho": [{"Bian": {}}],
        "Scylla": [{"Io": {}}],
        "Kraken": [{"Isaak": {}}],
        "Lymnades": [{"Kasa": {}}],
        "Chrysaor": [{"Krishna": {}}],
        "Sirene": [{"Sorento": {}}]
      }
    },
    "Specters": {
      "EvilStars": {
        "HeavenlyStars": [
          {"Star": "Tenkai(Star Chief Star of Heaven)", "Name": "Song Jiang", "Specters": [{"Yohma de Mephistopheles": {}}]},
          {"Star": "Tengou(Star of Conflagration)", "Name": "Lu Junyi", "Specters": []},
          {"Star": "Tenki(Star of Wisdom)", "Name": "Wu Yong", "Specters": []},
          {"Star": "Tenkan(Star of Idleness)", "Name": "Gongsun Sheng", "Specters": [{"Caronte de Aqueronte": {}}]},
          {"Star": "Ten'yuu(Star of Bravery)", "Name": "Guan Sheng", "Specters": []},
          {"Star": "Ten'yuu(Star of Heroic Ferocity)", "Name": "Lin Chong", "Specters": [
            {"Aiacos de Garuda": {}},
            {"Suikyo de Garuda": {}}]},
          {"Star": "Tenmou(Star of Swift Courage)", "Name": "Qin Ming", "Specters": [{"Radamanthys de Wyvern": {}}]},
          {"Star": "Ten'i(Star of Majesty)", "Name": "Huyan Zhuo", "Specters": [{"Lune de Balron": {}}]},
          {"Star": "Ten'ei(Heroic Star)", "Name": "Hua Rong", "Specters": []},
          {"Star": "Ten'ei(Lofty Star)", "Name": "Chai Jin", "Specters": [{"Minos de Grifo": {}}, 
            {"Vermeer de Griffon": {}}]},
          {"Star": "Tenfu(Star of Wealth)", "Name": "Li Ying", "Specters": []},
          {"Star": "Tenman(Star of Abundance)", "Name": "Zhu Tong", "Specters": []},
          {"Star": "Tenko(Lone Star)", "Name": "Lu ZhishenLu Zhishen", "Specters": [{"Violate de Behemoth": {}}]},
          {"Star": "Tenshou(Wounded Star)", "Name": "Wu Song", "Specters": [{"Fiodor de Mandrágora": {}}]},
          {"Star": "Tenritsu(Star of the Standing Spear)", "Name": "Dong Ping", "Specters": [{"Luko de Dríade": {}}]},
          {"Star": "Tenshou(The Swift Star)", "Name": "Zhang Qing", "Specters": [{"Sylphid de Basilisco": {}}, {"Sylphid de Basilisco (Lost Canvas)": {}}]},
          {"Star": "Ten'an(Dark Star)", "Name": "Yang Zhi", "Specters": [{"Moe": {"Midia": ["Saint Seiya Online"]}}]},
          {"Star": "Ten'yuu(Guardian Star)", "Name": "Yang Zhi", "Specters": []},
          {"Star": "Tenkuu(Empty Star)", "Name": "Suo Chao", "Specters": []},
          {"Star": "Tensoku(Speedy Star)", "Name": "Dai Zong", "Specters": []},
          {"Star": "Ten'i(Strange Star)", "Name": "Liu Tang", "Specters": [{"Curly": {"Midia": ["Saint Seiya Online"]}}]},
          {"Star": "Tensatsu(Murderous Star)", "Name": "Li Kui", "Specters": [{"Steven": {}}]},
          {"Star": "Tenbi(Lowly Star)", "Name": "Shi Jin", "Specters": []},
          {"Star": "Tenkyuu(Lewd Star)", "Name": "Mu Hong", "Specters": [{"Veronica de Nasu": {}}]},
          {"Star": "Tentai(Retreating Star)", "Name": "Lei Heng", "Specters": [{"Gregor de Genbu": {}}]},
          {"Star": "Tenju(Star of Longevity)", "Name": "Li Jun", "Specters": [{"Earheart de Vampiro": {}}]},
          {"Star": "Tenken(Dagger Star)", "Name": "Ruan Xiaoer", "Specters": []},
          {"Star": "Tenhei(Leveled Star)", "Name": "Zhang Shun", "Specters": [{"Chris de Cetus": {}}]},
          {"Star": "Tenzai(Star of Sin)", "Name": "Ruan Xiaowu", "Specters": [{"Flégias de Lycaon": {}}, {"Flégias de Lycaon (Lost Canvas)": {}}]},
          {"Star": "Tenson(Broken Star)", "Name": "Zhang Heng", "Specters": []},
          {"Star": "Tenpai(The Vanquished Star)", "Name": "Ruan Xiaoqi", "Specters": [{"Iwan de Troll": {}}]},
          {"Star": "Tenrou(The Goal Star)", "Name": "Yang Xiong", "Specters": [{"Gordon de Minotauro": {}}]},
          {"Star": "Tensui(Star of Intelligence)", "Name": "Shi Xiu", "Specters": []},
          {"Star": "Tenbou(Savage Star)", "Name": "Xie Zhen", "Specters": [{"Kagaho de Benu": {}}]},
          {"Star": "Tenkoku(Wailing Star)", "Name": "Xie Bao", "Specters": [{"Valentine de Harpia": {}}]},
          {"Star": "Tenkou(Clever Star)", "Name": "Yan Qing", "Specters": [{"Tokusa de Hanuman": {}}]}
        ],
        "EarthlyStars": [
          {"Star": "Chikai(Chief Star of Earth)", "Name": "Zhu Wu", "Specters": [{"Atavaka": {}}]},
          {"Star": "Chisatsu(Violent Star)", "Name": "Huang Xin", "Specters": []},
          {"Star": "Chiyuu(The Brave Star)", "Name": "Sun Li", "Specters": []},
          {"Star": "Chiketsu(Star of Noble Wisdom)", "Name": "Xuan Zan", "Specters": []},
          {"Star": "Chiyuu(The Heroic Star)", "Name": "Hao Siwen", "Specters": []},
          {"Star": "Chii(The Majestic Star)", "Name": "Han Tao", "Specters": [{"Estrela Terrestre do Prestígio ou Influência": {}}]},
          {"Star": "Chiei(Star of Courage)", "Name": "Peng Qi", "Specters": []},
          {"Star": "Chiki(The Strange Star)", "Name": "Shan Tinggui", "Specters": [{"Zelos de Sapo": {}},
            {"Zelos de Sapo (Lost Canvas)": {}},
            {"Meehan de Sapo": {}}]},
          {"Star": "Chimou(The Ferocious Star)", "Name": "Wei Dingguo", "Specters": [{"Espectro da Estrela Terrestre da Ferocidade ou Braveza": {}}]},
          {"Star": "Chibun(The Learned Star)", "Name": "Xiao Rang", "Specters": []},
          {"Star": "Chisei (The Guileless Star)", "Name": "Pei Xuan", "Specters": []},
          {"Star": "Chikatsu(The Eminent Star)", "Name": "Ou Peng", "Specters": [{"Kafka de Arlequim Mortal": {}}]},
          {"Star": "Chitou(The Folding Star)", "Name": "Deng Fei", "Specters": []},
          {"Star": "Chikyou(The Strong Star)", "Name": "Yan Shun", "Specters": []},
          {"Star": "Chian(The Dark Star)", "Name": "Yang Lin", "Specters": [{"Niobe de Deep": {}},
            {"Niobe de Deep (Lost Canvas)": {}}]},
          {"Star": "Chiziku(The Axis Star)", "Name": "Ling Zhen", "Specters": []},
          {"Star": "Chikai(The Star of Gathering)", "Name": "Jiang Jing", "Specters": []},
          {"Star": "Chisa(The Aiding Star)", "Name": "Lü Fang", "Specters": []},
          {"Star": "Chiyou(The Helpful Star)", "Name": "Guo Sheng", "Specters": []},
          {"Star": "Chirei(The Clever Star)", "Name": "An Daoquan", "Specters": [{"Espectro da Estrela Terrestre do Espírito (ou Assombração)": {}}]},
          {"Star": "Chiju(The Beast Star)", "Name": "Huangfu Duan", "Specters": [{"Cheshire de Cat Sith": {}}]},
          {"Star": "Chibi(The Least Star)", "Name": "Wang Ying", "Specters": []},
          {"Star": "Chikyu(The Intelligent Star)", "Name": "Hu San Niang", "Specters": []},
          {"Star": "Chibaku(The Barbarous Star)", "Name": "Bao Xu", "Specters": [{"Giganto de Ciclope": {}}]},
          {"Star": "Chizen(The Silent Star)", "Name": "Fan Rui", "Specters": []},
          {"Star": "Chikou(The Wild Star)", "Name": "Kong Ming", "Specters": []},
          {"Star": "Chikyou(The Star of Ambition)", "Name": "Kong Liang", "Specters": [{"Estrela Terrestre da Loucura": {}},
            {"Estrela Terrestre da Loucura (Lost Canvas)": {}}]},
          {"Star": "Chihi(The Flying Star)", "Name": "Xiang Chong", "Specters": [{"Edward de Silfo": {}}]},
          {"Star": "Chisou(The Walking Star)", "Name": "Li Gun", "Specters": [{"Ox de Górgona": {}}]},
          {"Star": "(The Cunning Star)", "Name": "Jin Dajian", "Specters": []},
          {"Star": "Chimei(The Clear Star)", "Name": "Ma Lin", "Specters": [{"Espectro da Estrela Terrestre da Clareza (ou Luz)": {}}]},
          {"Star": "Chisin(The Forward Star)", "Name": "Tong Wei", "Specters": [{"Estrela Terrestre do Progresso": {}}]},
          {"Star": "Chitai(The Retreating Star)", "Name": "Tong Meng", "Specters": [{"Estrela Terrestre da Retirada (ou Recuo)": {}}]},
          {"Star": "Chiman(The Full Star)", "Name": "Meng Kang", "Specters": []},
          {"Star": "Chisui(The Fulfilled Star)", "Name": "Hou Jian", "Specters": [{"Espectro da Estrela Terrestre da Sucesso (ou Alcance)": {}}]},
          {"Star": "Chishuu(The Complete Star)", "Name": "Chen Da", "Specters": []},
          {"Star": "Chiin(The Hidden Star)", "Name": "Yang Chun", "Specters": [{"Espectro da Estrela Terrestre do Segredo (ou Posse)": {}}]},
          {"Star": "Chii(The Peculiar Star)", "Name": "Zheng Tianshou", "Specters": []},
          {"Star": "Chiri(The Star of Justice)", "Name": "Tao Zongwang", "Specters": [{"Espectro da Estrela Terrestre da Razão": {}}]},
          {"Star": "Chisyun(The Elegant Star)", "Name": "Song Qing", "Specters": []},
          {"Star": "Chiraku(The Star of Music)", "Name": "Yue He", "Specters": [{"Espectro da Estrela Terrestre da Música (ou Alegria)": {}}]},
          {"Star": "Chitatsu (The Quick Star)", "Name": "Gong Wang", "Specters": []},
          {"Star": "Chisoku(The Star of Haste)", "Name": "Ding Desun", "Specters": [{"Estrela Terrestre da Velocidade": {}}]},
          {"Star": "Chichin(The Supressing Star)", "Name": "Mu Chun", "Specters": [{"Kageboshi": {}}]},
          {"Star": "Chikei(The Halted Star)", "Name": "Cao Zheng", "Specters": []},
          {"Star": "Chima(The Devil Star)", "Name": "Song Wan", "Specters": []},
          {"Star": "Chiyou(The Magic Star)", "Name": "Du Qian", "Specters": [{"Myu de Pappilon (Borboleta)": {}}]},
          {"Star": "Chiyuu(The Obscure Star)", "Name": "Xue Yong", "Specters": []},
          {"Star": "Chifuku(The Hiding Star)", "Name": "Shi En", "Specters": [{"Laimi de Verme": {}}]},
          {"Star": "Chihi(The Orphan Star)", "Name": "Li Zhong", "Specters": []},
          {"Star": "Chikuu(The Empty Star)", "Name": "Zhou Tong", "Specters": [{"Estrela Terrestre do Vazio (Grupo do Minos)": {}}]},
          {"Star": "Chiko(The Lonely Star)", "Name": "Tang Long", "Specters": []},
          {"Star": "Chizen(The Finished Star)", "Name": "Du Xing", "Specters": []},
          {"Star": "Chitan(The Short Star)", "Name": "Zou Yuan", "Specters": []},
          {"Star": "Chikaku (The Corner Star)", "Name": "Zou Run", "Specters": []},
          {"Star": "Chishuu(The Prisoned Star)", "Name": "Zhu Gui", "Specters": [{"Gerald": {}},
            {"Leybold de Upyr": {}}]},
          {"Star": "Chizou(The Hoarding Star)", "Name": "Zhu Fu", "Specters": []},
          {"Star": "Chihei(The Smooth Star)", "Name": "Cai Fu", "Specters": []},
          {"Star": "Chison(The Wounded Star)", "Name": "Cai Qing", "Specters": []},
          {"Star": "Chido(The Serving Star)", "Name": "Li Li", "Specters": [
            {"Estrela Terrestre da Escravidão": {}},
            {"Estrela Terrestre da Escravidão (Grupo do Deathtoll)": {}},
            {"Estrela Terrestre da Escravidão (Lost Canvas)": {}}]},
          {"Star": "Chisatsu(The Searching Star)", "Name": "Li Yun", "Specters": [{"Wimber de Morcego": {}}]},
          {"Star": "Chiaku(The Fierce Star)", "Name": "Jiao Ting", "Specters": [{"Isolde": {}}]},
          {"Star": "Chishuu(The Ugly Star)", "Name": "Shi Yong", "Specters": []},
          {"Star": "Chisu(The Mathematic Star)", "Name": "Sun Xin", "Specters": [{"Espectro da Estrela Terrestre do Cálculo": {}}]},
          {"Star": "Chiin(The Shadowy Star)", "Name": "Gu Dasao", "Specters": [{"Kiew (Cube) de Durahan": {}}]},
          {"Star": "Chikei(The Avenging Star)", "Name": "Zhang Qing", "Specters": [{"Estrela Terrestre da Punição ou Castigo": {}}]},
          {"Star": "Chisou(The Strong Star)", "Name": "Sun Erniang", "Specters": []},
          {"Star": "Chiretsu(The Inferior Star)", "Name": "Wang Dingliu", "Specters": [{"Miles de Elfo": {}}]},
          {"Star": "Chiken(The Mighty Star)", "Name": "Yu Baosi", "Specters": []},
          {"Star": "Chimou(The Rat Star)", "Name": "Bai Sheng", "Specters": []},
          {"Star": "Chizoku(The Thieving Star)", "Name": "Shi Qian", "Specters": []},
          {"Star": "Chikou(The Dog Star)", "Name": "Duan Jingzhu", "Specters": []}
        ]
      },
      "Others": {
        "CelestialStars": [
          {"Star": "Chiju(The Beast Star)", "Name": "Huangfu Duan", "Specters": [{"Faraó de Esfinge": {}}]},
          {"Star": "Chima(The Devil Star)", "Name": "Song Wan", "Specters": [{"Queen de Alraune (Lost Canvas)": {}}]},
          {"Star": "Chishuu(The Ugly Star)", "Name": "Shi Yong", "Specters": [{"Stand de Besouro Mortal": {}}]},
          {"Star": "Chiin(The Shadowy Star)", "Name": "Gu Dasao", "Specters": [{"Larry da Estrela Celeste da Sombra": {}}]},
          {"Star": "Chikaku (The Corner Star)", "Name": "Zou Run", "Specters": [{"Rock de Golem": {}}]},
          {"Star": "Chirei(The Clever Star)", "Name": "An Daoquan", "Specters": [{"Byaku de Necromante": {}}]}
        ],
        "UnknownStars": [
          {"Star": "", "Name": "", "Specters": [{"Espectro de Gárgula": {}}]},
          {"Star": "", "Name": "", "Specters": [{"Shura de Baphomet": {}}]},
          {"Star": "", "Name": "", "Specters": [{"Executioner (Boia in Italian) Specter": {"FanMade": "Marco Albiero"}}]},
          {"Star": "", "Name": "", "Specters": [{"Leech (Sanguisuga in Italian) Specter": {"FanMade": "Marco Albiero"}}]},
          {"Star": "", "Name": "", "Specters": [{"Morax (Marax in Italian) Specter": {"FanMade": "Marco Albiero"}}]}
        ],
        "Other Servants": [
          {"Markino de Esqueleto": {"Rank": ["Soldier"]}},
          {"Pandora": {"Rank": ["General commander"]}}
        ],
        "Revived": [
          {"Afrodite de Peixes (Renegado)": {}},
          {"Algethi de Hércules (Renegado)": {}},
          {"Algol de Perseu (Renegado)": {}},
          {"Babel de Centauro (Renegado)": {}},
          {"Camus de Aquário (Renegado)": {}},
          {"Capella de Auriga (Renegado)": {}},
          {"Dante de Cérbero (Renegado)": {}},
          {"Dio de Mosca (Renegado)": {}},
          {"Espectro - Sagita (Lost Canvas)": {}},
          {"Máscara da Morte de Câncer (Renegado)": {}},
          {"Misty de Lagardo (Renegado)": {}},
          {"Mouses de Baleia (Renegado)": {}},
          {"Saga de Gêmeos (Renegado)": {}},
          {"Shion de Áries (Renegado)": {}},
          {"Shura de Capricórnio (Renegado)": {}}
        ]
      }
    },
    "PhobetorWarriors": [{"Felser do Terror Negro": {}}],
    "Anjos": { 
      "Anjos da Morte": [
        {"Ashtarote de Querubim": {}},
        {"Belzebu de Serafim": {}},
        {"Érigor de Virtude": {}},
        {"Lúcifer": {}},
        {"Moa de Trono": {}}
      ],
      "Celestiais": [
        {"Odisseu": {}},
        {"Teseu": {}},
        {"Tohma de Ícaro": {}}
      ]
    },
    "Gods": [
      {
        "GreekAndRoman": [
          {"Atena": [
            {"Saori Kido": {"Midia": "Classic"}},
            {"Sasha": {"Midia": "Lost Canvas"}},
            {"Aria": {"Midia": "Ômega"}}]},
          {"Poseidon": [{"Julian Solo": {}}, {"Serafina": {"Midia": "Lost Canvas"}}]},
          {"Apolo": [
              {"Apolo": {"Midia": "Heaven Chapter: Overture"}}, 
              {"Abel": {"Midia": "Legend of Crimson Youth"}}]},
          {"Artemis": {}},
          {"Éris": {}},
          {"Hades": [{"Shun": {}}, {"Alone": {"Midia": "Next Dimension"}}]},
          {"Thanatos": {}},
          {"Hypnos": {}},
          {"Fantasos": {"Midia": "Lost Canvas"}},
          {"Icelos": {"Midia": "Lost Canvas"}},
          {"Kairos": {"Midia": "Lost Canvas"}},
          {"Morfeu": {"Midia": "Lost Canvas"}},
          {"Oneiros": {"Midia": "Lost Canvas"}},
          {"Phobetor": {"Midia": "Lost Canvas"}},
          {"Ares": [
            {"Saga": {"Midia": "Saintia Sho"}},
            {"Marte": {"Midia": "Ômega"}},
            {"Ares": {"Midia": "Lost Canvas"}}]},
          {"Pallas": {"Midia": "Ômega"}},
          {"(Episódio G) Gaia": {}},
          {"(Episódio G) Pontos": {}},
          {"(Episódio G) Tártaro": {}},
          {"(Episódio G) Urano": {}},
          {"Cronos": "Make and reference to Titans collection"},
          {"Tífon": "Make and reference to Titans collection"}
        ]
      },
      {
        "Nordic": [
          {"Odin": [{"Seiya": {}}, {"Aiolia": {"Midia": "Soul of Gold"}}]},
          {"Loki (Deus)": {}}
        ]
      },
      {
        "Egyptian": [
          {"Anúbis": {"Midia": "Episode G"}},
          {"Apófis": {"Midia": "Episode G"}},
          {"Rá": {"Midia": "Episode G"}}
        ]
      },
      {"Celtic": [{"Crúaich (Balor)": {"Midia": "Lost Canvas"}}]},
      {"SumerianAndAcadium": [{"Apsu": {"Midia": "Ômega"}}]},
      {
        "Aztec": [
          {"Carbella (Quetzalcoatl)": {"Midia": "Lost Canvas"}},
          {"Wesda (Tezcalipoca)": {"Midia": "Lost Canvas"}}
        ]
      }
    ]
  }, 
  "Outros": {
    "Animais": [
      {"Adolf": {}},
      {"Blondie": {}},
      {"Cacatua da Paradox": {}},
      {"Cãozinho do Alone (Lost Canvas)": {}},
      {"Cérbero": {}},
      {"Cérbero (Animal - Lost Canvas)": {}},
      {"Coelho (Shina)": {}},
      {"Corvos (Jamian)": {}},
      {"Esquilo da Paradox": {}},
      {"Fadas do Submundo": {}},
      {"Goldie": {}},
      {"Guing": {}},
      {"Hayate": {}},
      {"Kokuto": {}},
      {"Lebre": {}},
      {"Lebre (história budista)": {}},
      {"Lobos do Fenrir": {}},
      {"Morcegos do Wimber": {}},
      {"Moscas da Verônica": {}},
      {"Pardais da Mudan": {}},
      {"Pássaro (Água da Vida)": {}},
      {"Pássaros da Paradox": {}},
      {"Pégaso": {}},
      {"Raposa (história budista)": {}},
      {"Tigre (Shaka)": {}},
      {"Urso (Geki)": {}},
      {"Urso (Hyoga)": {}},
      {"Urso e Peixe (história budista)": {}}
    ]
  },
  "Coadjuvantes ou secundários": [
    {"Adversário do Ohko #1": {}},
    {"Adversário do Ohko #2": {}},
    {"Atla": {}},
    {"Caro": {}},
    {"Centauros": {}},
    {"Cor Tauri": {}},
    {"Deles": {}},
    {"Discípulos do Albion": {}},
    {"Dr. Asamori Hakase": {}},
    {"Eiri": {}},
    {"Esqueletos de Jamiel": {}},
    {"Gladiador (Lost Canvas)": {}},
    {"Hao": {}},
    {"Hécate": {}},
    {"Hecatônquiros": {}},
    {"Héctor": {}},
    {"Jaki": {}},
    {"Jericho (Ciclone Diabólico)": {}},
    {"Jet": {}},
    {"Ji-Woo": {}},
    {"John Black": {}},
    {"Kiki": {}},
    {"Legionários de Rá": {}},
    {"Lithos": {}},
    {"Lyfia": {}},
    {"Mãe da Conner": {}},
    {"Mãe do Ahimsa": {}},
    {"Mãe do Gioca": {}},
    {"Maiya (Lost Canvas)": {}},
    {"Makoto": {}},
    {"Maria": {}},
    {"Marido da Garnet": {}},
    {"Médico da Fundação Graad #1": {}},
    {"Médicos da Fundação Graad": {}},
    {"Mestre Ares (Arles)": {}},
    {"Mestre do Sage e Hakurei": {}},
    {"Mi-Young": {}},
    {"Miko Hasegawa": {}},
    {"Mimiko": {}},
    {"Mine": {}},
    {"Minu": {}},
    {"Mirai": {}},
    {"Mischa": {}},
    {"Mito": {}},
    {"Mitsumasa Kido": {}},
    {"Muirgheas Lugh": {}},
    {"Natássia (Episódio G)": {}},
    {"Natássia (mãe do Hyoga)": {}},
    {"Náufrago (Sibéria)": {}},
    {"Nguyen": {}},
    {"Ninfas": {}},
    {"Nishiyama": {}},
    {"Padre (Lost Canvas)": {}},
    {"Pai da Agathia": {}},
    {"Pai da Fluorite": {}},
    {"Pai do Lacaille": {}},
    {"Pais do Alone e Sasha": {}},
    {"Pakia": {}},
    {"Palmer": {}},
    {"Paulo": {}},
    {"Pefko": {}},
    {"Pesce": {}},
    {"Phillip": {}},
    {"Pigro": {}},
    {"Raki": {}},
    {"Ray": {}},
    {"Rei Minos": {}},
    {"Repórter da NHA": {}},
    {"Repórter da NHK": {}},
    {"Rine": {}},
    {"Rumi": {}},
    {"Salo": {}},
    {"Seika": {}},
    {"Selene": {}},
    {"Selinsa": {}},
    {"Servas de Ares (Arles)": {}},
    {"Servente da Aria": {}},
    {"Shinato": {}},
    {"Shoryu": {}},
    {"Shunrei": {}},
    {"Soldado de Kohoutek": {}},
    {"Sra. Fraille": {}},
    {"Sui": {}},
    {"Suisho": {}},
    {"Takamichi": {}},
    {"Tatsumi": {}},
    {"Tatsuya": {}},
    {"Terrorista de Three Mile Island": {}},
    {"Tomoe": {}},
    {"Turistas na Grécia": {}},
    {"Ursula Walden": {}},
    {"Viajante (história budista)": {}},
    {"Vice-Diretor da Palaestra": {}},
    {"Viviane (Dama do Lago)": {}},
    {"Yilin": {}},
    {"Yoshimi Morigakure Masataka": {}},
    {"Yoshino Hino": {}},
    {"Alberich XIII": {}},
    {"Folken": {}},
    {"Freya (irmã da Hilda)": {}},
    {"Freya (irmã do Frey)": {}}
  ],
  "Soldados e candidatos a cavaleiros": [
    {"Ohko": {}},
    {"Cássios": {}},
    {"Gangsa": {}},
    {"Gioca": {}},
    {"Garan": {}},
    {"Georges": {}},
    {"Toki": {"Rank": ["Cavaleiro Fantasma de Éris"]}},
    {"Soldados do Santuário": {}}
  ]
}
