const clothVersions = [
  {"id": "version-andromeda-1", "rank": "Bronze", "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-andromeda-omega", "rank": "Bronze", "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-apus", "rank": "Bronze", "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-Aquarius", "rank": "Gold", "saintsId": ["Camus", "Dégel", "Krest", "Mystoria", "Tokisada"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-aquila", "rank": "Silver", "saintsId": ["Marin"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-aquila-omega", "rank": "Bronze", "saintsId": ["Yuna"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-ara", "rank": "Silver", "saintsId": ["Hakurei"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-ara", "rank": "Silver", "saintsId": ["Nikol"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-aries", "rank": "Gold", "saintsId": ["Avenir", "Guateguard", "Mu", "Shion"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-aries-omega", "rank": "Gold", "saintsId": ["Kiki"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-auriga", "rank": "Silver", "saintsId": ["Capella"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-auriga-omega", "rank": "Silver", "saintsId": ["Almaaz"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-bootes", "rank": "Silver", "saintsId": ["Bayer"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-caelum", "rank": "Silver", "saintsId": ["Michelangelo"], "version": "", "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-camelopardalis-lost-canvas", "rank": "Silver", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-camelopardalis-omega", "rank": "Silver", "saintsId": ["Bartschius"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-cancer", "rank": "Gold", "saintsId": ["Contador da Morte", "Lancelot", "Manigold", "Death Mask", "Sage"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-cancer-omega", "rank": "Gold", "saintsId": ["Contador da Morte", "Schiller"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-canes-venatici", "rank": "Silver", "saintsId": ["Asterion"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-canes-venatici-omega", "rank": "Silver", "saintsId": ["Miguel"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-canis-major", "rank": "Silver", "saintsId": ["Sírius"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-capricorn", "rank": "Gold", "saintsId": ["El Cid", "Izo", "Shura"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-capricorn-omega", "rank": "Gold", "saintsId": ["Ionia"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-carina-corona-saints", "rank": "Bronze", "saintsId": ["Atlas"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-cassiopeia-lost-canvas", "name": "Cassiopeia", "rank": "Bronze", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-cassiopeia-saintia-sho", "name": "Cassiopeia", "rank": "Bronze", "saintsId": ["Elda"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-centaurus", "rank": "Silver", "saintsId": ["Babel", "Alfa"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-cepheus", "rank": "Silver", "saintsId": ["Daidaros"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-cepheus-anime", "rank": "Silver", "saintsId": ["Albion"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-cetus", "rank": "Silver", "saintsId": ["Mouses"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-cetus-omega", "rank": "Silver", "saintsId": ["Menkar"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-chameleon", "rank": "Bronze", "saintsId": ["June"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-circinus", "rank": "Bronze", "saintsId": ["Hook"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-columba-online", "rank": "Silver", "saintsId": ["Gray"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-comas-berenices-corona-saints", "rank": "Bronze", "saintsId": ["Berengue"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-comas-berenices-hipermito-unknown-cloths", "rank": "Bronze", "saintsId": ["Mei"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-comas-berenices-online", "rank": "Silver", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-corona-australis-online", "rank": "Bronze", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-corona-borealis-omega", "rank": "Bronze", "saintsId": ["Dali"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-corona-borealis-saintia-sho", "rank": "Bronze", "saintsId": ["Katya"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-corona-borealis-online", "rank": "Bronze", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-corona-borealis-lost-canvas", "rank": "Silver", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-corvus", "rank": "Silver", "saintsId": ["Jamian"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-corvus-omega", "rank": "Silver", "saintsId": ["Johan"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-crater", "name": "Crater", "rank": "Silver", "saintsId": [], "version": "", "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-crater-next-dimension", "rank": "Silver", "saintsId": ["Suikyô"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-crater-online", "rank": "Silver", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-crux-eris-phantom", "rank": "Silver", "saintsId": ["Christ"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-crux-saintia-sho", "rank": "Silver", "saintsId": ["Georg"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-crux-omega", "rank": "Silver", "saintsId": ["Kazuma"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-crux-online", "rank": "Silver", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-cygnus", "rank": "Bronze", "saintsId": ["Hyoga"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-cygnus-episode-g", "rank": "Bronze", "saintsId": ["Isaak"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-delphinus-jisty-phantom", "rank": "Bronze", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-delphinus-omega", "rank": "Bronze", "saintsId": ["Guney"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-delphinus-lost-canvas", "rank": "Bronze", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-delphinus-saintia-sho", "rank": "Bronze", "saintsId": ["Mii"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-delphinus-online", "rank": "Bronze", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-dorado", "rank": "Bronze", "saintsId": ["Spear"], "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-draco-1", "rank": "Bronze", "saintsId": ["Shiryu"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-draco-omega", "rank": "Bronze", "saintsId": ["Ryuho"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-equuleus-omega", "rank": "Bronze", "saintsId": ["Celeris", "Kitalpha", "Subaru"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-equuleus-saintia-sho", "rank": "Bronze", "saintsId": ["Kyoko", "Shoko"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-eridanus-lost-canvas", "rank": "Bronze", "saintsId": [""], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-fornax-online", "rank": "Silver", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-gemini", "rank": "Gold", "saintsId": ["Abel", "Aspros", "Cain", "Defteros", "Saga", "Kanon"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-gemini", "rank": "Gold", "saintsId": ["Paradox", "Integra"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-grus", "rank": "Silver", "saintsId": ["Komachi", "Yuzuriha"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-heracles", "rank": "Silver", "saintsId": ["Algethi"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-horologium", "rank": "Silver", "saintsId": ["Tokisada"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-hydra", "rank": "Bronze", "saintsId": ["Ichi", "Curtis"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-hydrus-online", "rank": "Bronze", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-hydrus-omega", "rank": "Silver", "saintsId": ["Ichi"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-indus-lost-canvas", "rank": "Bronze", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-lacerta", "rank": "Silver", "saintsId": ["Misty"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-leo", "rank": "Gold", "saintsId": ["Aiolia", "Ilias", "Kaiser", "Regulus"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-leo-omega", "rank": "Gold", "saintsId": ["Mikene"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-leo-minor", "rank": "Bronze", "saintsId": ["Ban", "Bleriot"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-leo-minor", "rank": "Bronze", "saintsId": ["Souma"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-lepus-lost-canvas", "rank": "Silver", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-lepus-online", "rank": "Silver", "saintsId": ["Arne"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-libra", "rank": "Gold", "saintsId": ["Dohko", "Gembu", "Itia", "Shiryu"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-lupus", "rank": "Bronze", "saintsId": ["Nachi", "Junkers"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-lupus", "rank": "Bronze", "saintsId": ["Yoshitomi", "Haruto"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-lynx-omega", "rank": "Bronze", "saintsId": ["Mirapolos"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-lynx-episode-g", "rank": "Bronze", "saintsId": ["Retsu"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-lynx-corona-saints", "rank": "Bronze", "saintsId": ["Jaô"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-lyra", "rank": "Silver", "saintsId": ["Orfeu"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-lyra-eris-phantom", "rank": "Silver", "saintsId": ["Orfeu"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-mensa-online", "rank": "Silver", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-monoceros", "rank": "Bronze", "saintsId": ["Jabu"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-monoceros-lost-canvas", "rank": "Bronze", "saintsId": ["Yato"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-musca", "rank": "Silver", "saintsId": ["Dio"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-musca-omega", "rank": "Silver", "saintsId": ["Fly"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-norma", "rank": "Bronze", "saintsId": ["Luciano"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-ophiuchus", "rank": "Silver", "saintsId": ["Shina"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-ophiuchus-next-dimension", "rank": "Gold", "saintsId": ["Odisseu"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-orion-eris-phantom-1", "rank": "Silver", "saintsId": ["Jaga"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-orion-eris-phantom-2", "rank": "Silver", "saintsId": ["Rigel"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-orion", "rank": "Bronze", "saintsId": ["Eden"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-pavo-saintia-sho", "rank": "Bronze", "saintsId": ["Mayura"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-pavo-omega", "rank": "Silver", "saintsId": ["Plavin"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-pavo", "rank": "Silver", "saintsId": ["Shiva"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-pavo-online", "rank": "Silver", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-pegasus", "rank": "Bronze", "saintsId": ["Seiya", "Tenma", "Rodorio"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-pegasus-omega", "rank": "Bronze", "saintsId": ["Kouga"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-perseus", "rank": "Silver", "saintsId": ["Algol", "Mirfak"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-phoenix", "rank": "Bronze", "saintsId": ["Ikki"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-pisces", "rank": "Gold", "saintsId": ["Albafica", "Amor", "Cardinale", "Lugonis", "Afrodite"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-piscis-austrinus-online", "rank": "Bronze", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-puppis-lost-canvas", "rank": "Bronze", "saintsId": ["Lacaille"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-pyxis-lost-canvas", "rank": "Bronze", "saintsId": ["Rusk"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-reticulum", "rank": "Silver", "saintsId": ["Berlozzo"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-sagitta", "rank": "Silver", "saintsId": ["Tremy", "Maiya", "Siam", "Archon"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-sagittarius", "rank": "Gold", "saintsId": ["Aiolos", "Gestalt", "Seiya", "Sísifo"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-sagittarius-omega", "rank": "Gold", "saintsId": ["Seiya"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-scorpio", "rank": "Gold", "saintsId": ["Écarlate", "Kardia", "Milo", "Sonia", "Zafiri"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-scutum-eris-phantom", "rank": "Silver", "saintsId": ["Yan"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-scutum-omega", "rank": "Silver", "saintsId": ["Ennead"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-scutum-saintia-sho", "rank": "Silver", "saintsId": ["Juan"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-serpens-online", "rank": "Bronze", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-sextans", "rank": "Bronze", "saintsId": ["Yuuri"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-taurus", "rank": "Gold", "saintsId": ["Aldebaran", "Francisca", "Hasgard", "Ox", "Teneo"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-taurus-omega", "rank": "Gold", "saintsId": ["Harbinger"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-triangulum", "rank": "Silver", "saintsId": ["Noesis"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-tucana-lost-canvas", "rank": "Silver", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-ursa-major", "rank": "Bronze", "saintsId": ["Geki", "Douglas"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-ursa-minor", "rank": "Bronze", "saintsId": ["Xiaoling"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-velame", "rank": "Silver", "saintsId": ["Tsubaki"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-virgo", "rank": "Gold", "saintsId": ["Shaka", "Asmita", "Fudou", "Shijima"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-volans-online", "rank": "Bronze", "saintsId": ["Argo"], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-volans-lost-canvas", "rank": "Bronze", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-", "rank": "", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"},
  {"id": "version-", "rank": "", "saintsId": [], "appear": "URL image scene", "scheme": "URL image scheme"}
  
];     
      "NoConstellations": {
        "Reindeer ": {"Status": "Extinct", "BronzeSaints": [{"Rudolph de Rena": {}}]},
        "Cerberus": {
          "Status": "Extinct",
          "SilverSaints": [
            {"Cérbero (Lost Canvas, séc. 15)": {}},
            {"Cérbero (Lost Canvas)": {}},
            {"Dante de Cérbero": {}},
            {"Dorer de Cérbero": {}}
          ]
        },
        "Noctua": {"Status": "Extinct", "Unknown Cloths": [{"Partita de Coruja": {}}]},
        "Lotus": {"Status": "Constelação oriental da Índia", "SilverSaints": [{"Ágora de Lótus": {}}]},
        "Tarantula": {"SilverSaints": [{"Aracne de Tarântula": {}}]},
        "Cavaleiro do Fogo": {},
        "Spartan": {},
        "Reda": {},
        "Spika": {},
        "Dócrates": {},
        "Píton": {},
        "Gigars": {},
        "Mestre Cristal": {},
        "Mestre dos Fantasmas": {
          "SilverSaints": [
            {"Jisty": {}},
            {"Armadura de Mestre dos Fantasmas": {"Midia": "Saint Seiya Online"}}
          ]
        },
        "Medusa": {"Rank": ["Cavaleiro Fantasma de Jisty"]},
        "Serpente Marinha": {"Rank": ["Cavaleiro Fantasma de Jisty"]}
      }, 
      "Cavaleiros de Aço": [
        {"Ban de Leão Menor (Ômega)": {}},
        {"Daichi da Armadura da Terra": {}},
        {"Daichi da Armadura da Terra (Ômega)": {}},
        {"Emma": {}},
        {"Erna": {}},
        {"Geki de Urso (Ômega)": {}},
        {"Jabu de Unicórnio (Ômega)": {}},
        {"Kerry": {}},
        {"Nachi de Lobo (Ômega)": {}},
        {"Shô da Armadura do Céu": {}},
        {"Shô da Armadura do Céu (Ômega)": {}},
        {"Subaru de Cavalo Menor": {}},
        {"Ushô da Armadura da Água (Ômega)": {}},
        {"Ushô da Armadura do Mar": {}}
      ],
      "Cavaleiros Negros": [
        {"Allegre de Baleia Negra": {}},
        {"Andrômeda Negro": {}},
        {"Cavaleiros Negros": {}},
        {"Don Avido de Altar Negro": {}},
        {"Guilty": {}},
        {"Jango": {}},
        {"Jid de Cisne Negro": {}},
        {"Kenuma de Pégaso Negro": {}},
        {"Lemargos de Hércules Negro": {}},
        {"Lumaca": {}},
        {"Ritahoa de Fênix Negro": {}},
        {"Rusé de Corvo Negro": {}},
        {"Shinadekuro de Dragão Negro": {}},
        {"Yudo de Cães de Caça Negro": {}}
      ]
    },