export const cloths = [
  {"id": "cloth-Andromeda", "Name": "Andromeda", "EnglishName": "Andromeda", "versionsId": ["version-andromeda-1", "version-andromeda-omega"]},
  {"id": "cloth-Antlia", "Name": "Antlia", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Apus", "Name": "Apus", "EnglishName": "", "versionsId": ["version-apus"]},
  {"id": "cloth-Aquarius", "Name": "Aquarius", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Aquila", "Name": "Aquila", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Ara", "Name": "Ara", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Aries", "Name": "Aries", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Auriga", "Name": "Auriga", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Bootes", "Name": "Böotes", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Caelum", "Name": "Caelum", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Camelopardalis", "Name": "Camelopardalis", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Cancer", "Name": "Cancer", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Canes-Venatici", "Name": "Canes Venatici", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Canis-Major", "Name": "Canis Major", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Canis-Minor", "Name": "Canis Minor", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Capricorn", "Name": "Capricorn", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Carina", "Name": "Carina", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Cassiopeia", "Name": "Cassiopeia", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Centaurus", "Name": "Centaurus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Cepheus", "Name": "Cepheus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Cetus", "Name": "Cetus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Chameleon", "Name": "Chameleon", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Circinus", "Name": "Circinus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Columba", "Name": "Columba", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Comas-Berenices", "Name": "Comas Berenices", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Corona-Australis", "Name": "Corona Australis", "EnglishName": "", "versionsId": ["version-corona-australis-online"]},
  {"id": "cloth-Corona-Borealis", "Name": "Corona Borealis", "EnglishName": "", "versionsId": ["version-corona-borealis-omega", "version-corona-borealis-saintia-sho", "version-corona-borealis-online", "version-corona-borealis-lost-canvas"]},
  {"id": "cloth-Corvus", "Name": "Corvus", "EnglishName": "", "versionsId": ["version-corvus", "version-corvus-omega"]},
  {"id": "cloth-Crater", "Name": "Crater", "EnglishName": "", "versionsId": ["version-crater", "version-crater-online", "version-crater-next-dimension"]},
  {"id": "cloth-Crux", "Name": "Crux", "EnglishName": "", "versionsId": ["version-crux-eris-phantom", "version-crux-saintia-sho", "version-crux-omega", "version-crux-online"]},
  {"id": "cloth-Cygnus", "Name": "Cygnus", "EnglishName": "", "versionsId": ["version-cygnus", "version-cygnus-episode-g"]},
  {"id": "cloth-Delphinus", "Name": "Delphinus", "EnglishName": "", "versionsId": ["version-delphinus-jisty-phantom", "version-delphinus-omega", "version-delphinus-lost-canvas", "version-delphinus-saintia-sho", "version-delphinus-online"]},
  {"id": "cloth-Dorado", "Name": "Dorado", "EnglishName": "", "versionsId": ["version-dorado"]},
  {"id": "cloth-Draco", "Name": "Draco", "EnglishName": "", "versionsId": ["version-draco-1", "version-draco-omega"]},
  {"id": "cloth-Equuleus", "Name": "Equuleus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Eridanus", "Name": "Eridanus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Fornax", "Name": "Fornax", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Gemini", "Name": "Gemini", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Grus", "Name": "Grus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Heracles", "Name": "Heracles", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Horologium", "Name": "Horologium", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Hydra", "Name": "Hydra", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Hydrus", "Name": "Hydrus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Indus", "Name": "Indus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Lacerta", "Name": "Lacerta", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Leo", "Name": "Leo", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Leo-Minor", "Name": "Leo Minor", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Lepus", "Name": "Lepus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Libra", "Name": "Libra", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Lupus", "Name": "Lupus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Lynx", "Name": "Lynx", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Lyra", "Name": "Lyra", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Mensa", "Name": "Mensa", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Microscopium", "Name": "Microscopium", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Monoceros", "Name": "Monoceros", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Musca", "Name": "Musca", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Norma", "Name": "Norma", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Octans", "Name": "Octans", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Ophiuchus", "Name": "Ophiuchus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Orion", "Name": "Orion", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Pavo", "Name": "Pavo", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Pegasus", "Name": "Pegasus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Perseus", "Name": "Perseus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Phoenix", "Name": "Phoenix", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Pictor", "Name": "Pictor", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Pisces", "Name": "Pisces", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Piscis-Austrinus", "Name": "Piscis Austrinus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Puppis", "Name": "Puppis", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Pyxis", "Name": "Pyxis", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Reticulum", "Name": "Reticulum", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Sagitta", "Name": "Sagitta", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Sagittarius", "Name": "Sagittarius", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Scorpio", "Name": "Scorpio", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Sculptor", "Name": "Sculptor", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Scutum", "Name": "Scutum", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Serpens", "Name": "Serpens", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Sextans", "Name": "Sextans", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Taurus", "Name": "Taurus", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Telescopium", "Name": "Telescopium", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Triangulum", "Name": "Triangulum", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Triangulum-Australe", "Name": "Triangulum Australe", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Tucana", "Name": "Tucana", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Ursa-Major", "Name": "Ursa Major", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Ursa-Minor", "Name": "Ursa Minor", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Velame", "Name": "Velame", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Virgo", "Name": "Virgo", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Volans", "Name": "Volans", "EnglishName": "", "versionsId": []},
  {"id": "cloth-Vulpecula", "Name": "Vulpecula", "EnglishName": "", "versionsId": []}
];  

  