export const constellations = [
  {"id": "Constellation-Andromeda", "Name": "Andromeda", "EnglishName": "Andromeda"},
  {"id": "Constellation-Antlia", "Name": "Antlia", "EnglishName": ""},
  {"id": "Constellation-Apus", "Name": "Apus", "EnglishName": ""},
  {"id": "Constellation-Aquarius", "Name": "Aquarius", "EnglishName": ""},
  {"id": "Constellation-Aquila", "Name": "Aquila", "EnglishName": ""},
  {"id": "Constellation-Ara", "Name": "Ara", "EnglishName": ""},
  {"id": "Constellation-Aries", "Name": "Aries", "EnglishName": ""},
  {"id": "Constellation-Auriga", "Name": "Auriga", "EnglishName": ""},
  {"id": "Constellation-Bootes", "Name": "Böotes", "EnglishName": ""},
  {"id": "Constellation-Caelum", "Name": "Caelum", "EnglishName": ""},
  {"id": "Constellation-Camelopardalis", "Name": "Camelopardalis", "EnglishName": ""},
  {"id": "Constellation-Cancer", "Name": "Cancer", "EnglishName": ""},
  {"id": "Constellation-Canes-Venatici", "Name": "Canes Venatici", "EnglishName": ""},
  {"id": "Constellation-Canis-Major", "Name": "Canis Major", "EnglishName": ""},
  {"id": "Constellation-Canis-Minor", "Name": "Canis Minor", "EnglishName": ""},
  {"id": "Constellation-Capricorn", "Name": "Capricorn", "EnglishName": ""},
  {"id": "Constellation-Carina", "Name": "Carina", "EnglishName": ""},
  {"id": "Constellation-Cassiopeia", "Name": "Cassiopeia", "EnglishName": ""},
  {"id": "Constellation-Centaurus", "Name": "Centaurus", "EnglishName": ""},
  {"id": "Constellation-Cepheus", "Name": "Cepheus", "EnglishName": ""},
  {"id": "Constellation-Cetus", "Name": "Cetus", "EnglishName": ""},
  {"id": "Constellation-Chameleon", "Name": "Chameleon", "EnglishName": ""},
  {"id": "Constellation-Circinus", "Name": "Circinus", "EnglishName": ""},
  {"id": "Constellation-Columba", "Name": "Columba", "EnglishName": ""},
  {"id": "Constellation-Comas-Berenices", "Name": "Comas Berenices", "EnglishName": ""},
  {"id": "Constellation-Corona-Australis", "Name": "Corona Australis", "EnglishName": ""},
  {"id": "Constellation-Corona-Borealis", "Name": "Corona Borealis", "EnglishName": ""},
  {"id": "Constellation-Corvus", "Name": "Corvus", "EnglishName": ""},
  {"id": "Constellation-Crater", "Name": "Crater", "EnglishName": ""},
  {"id": "Constellation-Crux", "Name": "Crux", "EnglishName": ""},
  {"id": "Constellation-Cygnus", "Name": "Cygnus", "EnglishName": ""},
  {"id": "Constellation-Delphinus", "Name": "Delphinus", "EnglishName": ""},
  {"id": "Constellation-Dorado", "Name": "Dorado", "EnglishName": ""},
  {"id": "Constellation-Draco", "Name": "Draco", "EnglishName": ""},
  {"id": "Constellation-Equuleus", "Name": "Equuleus", "EnglishName": ""},
  {"id": "Constellation-Eridanus", "Name": "Eridanus", "EnglishName": ""},
  {"id": "Constellation-Fornax", "Name": "Fornax", "EnglishName": ""},
  {"id": "Constellation-Gemini", "Name": "Gemini", "EnglishName": ""},
  {"id": "Constellation-Grus", "Name": "Grus", "EnglishName": ""},
  {"id": "Constellation-Heracles", "Name": "Heracles", "EnglishName": ""},
  {"id": "Constellation-Horologium", "Name": "Horologium", "EnglishName": ""},
  {"id": "Constellation-Hydra", "Name": "Hydra", "EnglishName": ""},
  {"id": "Constellation-Hydrus", "Name": "Hydrus", "EnglishName": ""},
  {"id": "Constellation-Indus", "Name": "Indus", "EnglishName": ""},
  {"id": "Constellation-Lacerta", "Name": "Lacerta", "EnglishName": ""},
  {"id": "Constellation-Leo", "Name": "Leo", "EnglishName": ""},
  {"id": "Constellation-Leo-Minor", "Name": "Leo Minor", "EnglishName": ""},
  {"id": "Constellation-Lepus", "Name": "Lepus", "EnglishName": ""},
  {"id": "Constellation-Libra", "Name": "Libra", "EnglishName": ""},
  {"id": "Constellation-Lupus", "Name": "Lupus", "EnglishName": ""},
  {"id": "Constellation-Lynx", "Name": "Lynx", "EnglishName": ""},
  {"id": "Constellation-Lyra", "Name": "Lyra", "EnglishName": ""},
  {"id": "Constellation-Mensa", "Name": "Mensa", "EnglishName": ""},
  {"id": "Constellation-Microscopium", "Name": "Microscopium", "EnglishName": ""},
  {"id": "Constellation-Monoceros", "Name": "Monoceros", "EnglishName": ""},
  {"id": "Constellation-Musca", "Name": "Musca", "EnglishName": ""},
  {"id": "Constellation-Norma", "Name": "Norma", "EnglishName": ""},
  {"id": "Constellation-Octans", "Name": "Octans", "EnglishName": ""},
  {"id": "Constellation-Ophiuchus", "Name": "Ophiuchus", "EnglishName": ""},
  {"id": "Constellation-Orion", "Name": "Orion", "EnglishName": ""},
  {"id": "Constellation-Pavo", "Name": "Pavo", "EnglishName": ""},
  {"id": "Constellation-Pegasus", "Name": "Pegasus", "EnglishName": ""},
  {"id": "Constellation-Perseus", "Name": "Perseus", "EnglishName": ""},
  {"id": "Constellation-Phoenix", "Name": "Phoenix", "EnglishName": ""},
  {"id": "Constellation-Pictor", "Name": "Pictor", "EnglishName": ""},
  {"id": "Constellation-Pisces", "Name": "Pisces", "EnglishName": ""},
  {"id": "Constellation-Piscis-Austrinus", "Name": "Piscis Austrinus", "EnglishName": ""},
  {"id": "Constellation-Puppis", "Name": "Puppis", "EnglishName": ""},
  {"id": "Constellation-Pyxis", "Name": "Pyxis", "EnglishName": ""},
  {"id": "Constellation-Reticulum", "Name": "Reticulum", "EnglishName": ""},
  {"id": "Constellation-Sagitta", "Name": "Sagitta", "EnglishName": ""},
  {"id": "Constellation-Sagittarius", "Name": "Sagittarius", "EnglishName": ""},
  {"id": "Constellation-Scorpio", "Name": "Scorpio", "EnglishName": ""},
  {"id": "Constellation-Sculptor", "Name": "Sculptor", "EnglishName": ""},
  {"id": "Constellation-Scutum", "Name": "Scutum", "EnglishName": ""},
  {"id": "Constellation-Serpens", "Name": "Serpens", "EnglishName": ""},
  {"id": "Constellation-Sextans", "Name": "Sextans", "EnglishName": ""},
  {"id": "Constellation-Taurus", "Name": "Taurus", "EnglishName": ""},
  {"id": "Constellation-Telescopium", "Name": "Telescopium", "EnglishName": ""},
  {"id": "Constellation-Triangulum", "Name": "Triangulum", "EnglishName": ""},
  {"id": "Constellation-Triangulum-Australe", "Name": "Triangulum Australe", "EnglishName": ""},
  {"id": "Constellation-Tucana", "Name": "Tucana", "EnglishName": ""},
  {"id": "Constellation-Ursa-Major", "Name": "Ursa Major", "EnglishName": ""},
  {"id": "Constellation-Ursa-Minor", "Name": "Ursa Minor", "EnglishName": ""},
  {"id": "Constellation-Velame", "Name": "Velame", "EnglishName": ""},
  {"id": "Constellation-Virgo", "Name": "Virgo", "EnglishName": ""},
  {"id": "Constellation-Volans", "Name": "Volans", "EnglishName": ""},
  {"id": "Constellation-Vulpecula", "Name": "Vulpecula", "EnglishName": ""}
];