export const constellations = [
  {"id": "Constellation-Andromeda", "Name": "Andromeda", "Saints": [], "EnglishName": "Andromeda"},
  {"id": "Constellation-Antlia", "Name": "Antlia", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Apus", "Name": "Apus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Aquarius", "Name": "Aquarius", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Aquila", "Name": "Aquila", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Ara", "Name": "Ara", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Aries", "Name": "Aries", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Auriga", "Name": "Auriga", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Bootes", "Name": "Böotes", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Caelum", "Name": "Caelum", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Camelopardalis", "Name": "Camelopardalis", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Cancer", "Name": "Cancer", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Canes-Venatici", "Name": "Canes Venatici", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Canis-Major", "Name": "Canis Major", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Canis-Minor", "Name": "Canis Minor", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Capricorn", "Name": "Capricorn", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Carina", "Name": "Carina", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Cassiopeia", "Name": "Cassiopeia", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Centaurus", "Name": "Centaurus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Cepheus", "Name": "Cepheus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Cetus", "Name": "Cetus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Chameleon", "Name": "Chameleon", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Circinus", "Name": "Circinus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Columba", "Name": "Columba", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Comas-Berenices", "Name": "Comas Berenices", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Corona-Australis", "Name": "Corona Australis", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Corona-Borealis", "Name": "Corona Borealis", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Corvus", "Name": "Corvus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Crater", "Name": "Crater", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Crux", "Name": "Crux", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Cygnus", "Name": "Cygnus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Delphinus", "Name": "Delphinus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Dorado", "Name": "Dorado", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Draco", "Name": "Draco", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Equuleus", "Name": "Equuleus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Eridanus", "Name": "Eridanus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Fornax", "Name": "Fornax", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Gemini", "Name": "Gemini", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Grus", "Name": "Grus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Heracles", "Name": "Heracles", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Horologium", "Name": "Horologium", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Hydra", "Name": "Hydra", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Hydrus", "Name": "Hydrus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Indus", "Name": "Indus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Lacerta", "Name": "Lacerta", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Leo", "Name": "Leo", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Leo-Minor", "Name": "Leo Minor", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Lepus", "Name": "Lepus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Libra", "Name": "Libra", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Lupus", "Name": "Lupus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Lynx", "Name": "Lynx", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Lyra", "Name": "Lyra", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Mensa", "Name": "Mensa", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Microscopium", "Name": "Microscopium", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Monoceros", "Name": "Monoceros", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Musca", "Name": "Musca", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Norma", "Name": "Norma", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Octans", "Name": "Octans", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Ophiuchus", "Name": "Ophiuchus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Orion", "Name": "Orion", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Pavo", "Name": "Pavo", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Pegasus", "Name": "Pegasus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Perseus", "Name": "Perseus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Phoenix", "Name": "Phoenix", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Pictor", "Name": "Pictor", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Pisces", "Name": "Pisces", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Piscis-Austrinus", "Name": "Piscis Austrinus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Puppis", "Name": "Puppis", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Pyxis", "Name": "Pyxis", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Reticulum", "Name": "Reticulum", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Sagitta", "Name": "Sagitta", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Sagittarius", "Name": "Sagittarius", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Scorpio", "Name": "Scorpio", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Sculptor", "Name": "Sculptor", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Scutum", "Name": "Scutum", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Serpens", "Name": "Serpens", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Sextans", "Name": "Sextans", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Taurus", "Name": "Taurus", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Telescopium", "Name": "Telescopium", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Triangulum", "Name": "Triangulum", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Triangulum-Australe", "Name": "Triangulum Australe", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Tucana", "Name": "Tucana", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Ursa-Major", "Name": "Ursa Major", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Ursa-Minor", "Name": "Ursa Minor", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Velame", "Name": "Velame", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Virgo", "Name": "Virgo", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Volans", "Name": "Volans", "Saints": [], "EnglishName": ""},
  {"id": "Constellation-Vulpecula", "Name": "Vulpecula", "Saints": [], "EnglishName": ""}
];